[build]
builder = "NIXPACKS"
buildCommand = "bun install && bun run build:railway"

[deploy]
startCommand = "bun run preview"
healthcheckPath = "/"
healthcheckTimeout = 300

[env]
NODE_ENV = "production"
NODE_VERSION = "18"
BUN_VERSION = "1.2.11"

[networking]
serviceDomain = "artelouarrate-frontend"