[build]
builder = "NIXPACKS"
buildCommand = "bun install --frozen-lockfile && bun run build"

[deploy]
startCommand = "bun run preview"
healthcheckPath = "/"
healthcheckTimeout = 300

[env]
NODE_ENV = "production"
NODE_VERSION = "18"
BUN_VERSION = "1.0.0"

[networking]
serviceDomain = "artelouarrate-frontend"