[build]
builder = "NIXPACKS"
buildCommand = "npm install --legacy-peer-deps && npm run build"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
NEXT_PUBLIC_API_URL = "${{BACKEND_URL}}/api"

[[services]]
[services.frontend]
source = "."
domains = ["your-frontend-domain.railway.app"]

[build.env]
NODE_VERSION = "18" 