[build]
builder = "NIXPACKS"
buildCommand = "bun install && bun run build:railway"

[deploy]
startCommand = "npx vite preview --port $PORT --host 0.0.0.0"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
NODE_VERSION = "18"
BUN_VERSION = "1.2.11"
NODE_OPTIONS = "--max-old-space-size=4096"

[networking]
serviceDomain = "artelouarrate-frontend"