[build]
builder = "NIXPACKS"
buildCommand = "npm install && npm run build"

[deploy]
startCommand = "npm run preview"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

[env]
NODE_ENV = "production"
PORT = "$PORT"
VITE_API_URL = "https://artelouarate-backend-production.up.railway.app"

[networking]
serviceDomain = "artelouarrate-frontend"