[build]
builder = "NIXPACKS"
buildCommand = "npm ci --omit=dev && npm run build"

[deploy]
startCommand = "npm run preview"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
NODE_VERSION = "18"
NODE_OPTIONS = "--max-old-space-size=4096"
NPM_CONFIG_PROGRESS = "false"
NPM_CONFIG_FUND = "false"
NPM_CONFIG_AUDIT = "false"

[networking]
serviceDomain = "artelouarrate-frontend"