[build]
builder = "NIXPACKS"
buildCommand = "npm ci && npm run build"

[deploy]
startCommand = "npm run preview"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
VITE_API_URL = "https://artelouarate-backend-production.up.railway.app"

[build.env]
NODE_OPTIONS = "--max-old-space-size=4096" 